= 各个业务工程地址

	civet-app:
		base:		http://192.168.18.14:81/platform-architecture.civet-app/civet-base.git
		            git@192.168.18.14:platform-architecture.civet-app/civet-base.git
		mobile:		http://192.168.18.14:81/platform-architecture.civet-app/civet-mobile.git    (部署包)
		            git@192.168.18.14:platform-architecture.civet-app/civet-mobile.git
		scheduler：	http://192.168.18.14:81/platform-architecture.civet-app/civet-scheduler.git (部署包)
		            git@192.168.18.14:platform-architecture.civet-app/civet-scheduler.git
		user:
			api:	http://192.168.18.14:81/platform-architecture.civet-app.user/civet-user-api.git
			        git@192.168.18.14:platform-architecture.civet-app.user/civet-user-api.git
			impl:	http://192.168.18.14:81/platform-architecture.civet-app.user/civet-user-impl.git    (部署包)
			        git@192.168.18.14:platform-architecture.civet-app.user/civet-user-impl.git
		trade:
			api:	http://192.168.18.14:81/platform-architecture.civet-app.trade/civet-trade-api.git
			        git@192.168.18.14:platform-architecture.civet-app.trade/civet-trade-api.git
			impl:	http://192.168.18.14:81/platform-architecture.civet-app.trade/civet-trade-impl.git  (部署包)
			        git@192.168.18.14:platform-architecture.civet-app.trade/civet-trade-impl.git
		account:
			api:	http://192.168.18.14:81/platform-architecture.civet-app.account/civet-account-api.git
			        git@192.168.18.14:platform-architecture.civet-app.account/civet-account-api.git
			impl:	http://192.168.18.14:81/platform-architecture.civet-app.account/civet-account-impl.git  (部署包)
			        git@192.168.18.14:platform-architecture.civet-app.account/civet-account-impl.git
		sysconf:
			api:	http://192.168.18.14:81/platform-architecture.civet-app.sysconf/civet-sysconf-api.git
			        git@192.168.18.14:platform-architecture.civet-app.sysconf/civet-sysconf-api.git
			impl:	http://192.168.18.14:81/platform-architecture.civet-app.sysconf/civet-sysconf-impl.git  (部署包)
			        git@192.168.18.14:platform-architecture.civet-app.sysconf/civet-sysconf-impl.git
		snapdata:
			api:	http://192.168.18.14:81/platform-architecture.civet-app.snapdata/civet-snapdata-api.git
			        git@192.168.18.14:platform-architecture.civet-app.snapdata/civet-snapdata-api.git
			impl:	http://192.168.18.14:81/platform-architecture.civet-app.snapdata/civet-snapdata-impl.git    (部署包)
			        git@192.168.18.14:platform-architecture.civet-app.snapdata/civet-snapdata-impl.git


	civet-manage:
		web:		http://192.168.18.14:81/platform-architecture.civet-manage/civet-manage-web.git (部署包)
		            git@192.168.18.14:platform-architecture.civet-manage/civet-manage-web.git
		scheduler：	http://192.168.18.14:81/platform-architecture.civet-manage/civet-manage-scheduler.git   (部署包)
		            git@192.168.18.14:platform-architecture.civet-manage/civet-manage-scheduler.git
		user:
			api:	http://192.168.18.14:81/platform-architecture.civet-manage.user/civet-manage-user-api.git
			        git@192.168.18.14:platform-architecture.civet-manage.user/civet-manage-user-api.git
			impl:	http://192.168.18.14:81/platform-architecture.civet-manage.user/civet-manage-user-impl.git  (部署包)
			        git@192.168.18.14:platform-architecture.civet-manage.user/civet-manage-user-impl.git
		trade:
			api:	http://192.168.18.14:81/platform-architecture.civet-manage.trade/civet-manage-trade-api.git
			        git@192.168.18.14:platform-architecture.civet-manage.trade/civet-manage-trade-api.git
			impl:	http://192.168.18.14:81/platform-architecture.civet-manage.trade/civet-manage-trade-impl.git    (部署包)
			        git@192.168.18.14:platform-architecture.civet-manage.trade/civet-manage-trade-impl.git
		account:
			api:	http://192.168.18.14:81/platform-architecture.civet-manage.account/civet-manage-account-api.git
			        git@192.168.18.14:platform-architecture.civet-manage.account/civet-manage-account-api.git
			impl:	http://192.168.18.14:81/platform-architecture.civet-manage.account/civet-manage-account-impl.git    (部署包)
			        git@192.168.18.14:platform-architecture.civet-manage.account/civet-manage-account-impl.git
		sys:
			api:	http://192.168.18.14:81/platform-architecture.civet-manage.sys/civet-manage-sys-api.git
			        git@192.168.18.14:platform-architecture.civet-manage.sys/civet-manage-sys-api.git
			impl:	http://192.168.18.14:81/platform-architecture.civet-manage.sys/civet-manage-sys-impl.git    (部署包)
			        git@192.168.18.14:platform-architecture.civet-manage.sys/civet-manage-sys-impl.git
		snapdata:
			api:	http://192.168.18.14:81/platform-architecture.civet-manage.snapdata/civet-manage-snapdata-api.git
			        git@192.168.18.14:platform-architecture.civet-manage.snapdata/civet-manage-snapdata-api.git
			impl:	http://192.168.18.14:81/platform-architecture.civet-manage.snapdata/civet-manage-snapdata-impl.git  (部署包)
			        git@192.168.18.14:platform-architecture.civet-manage.snapdata/civet-manage-snapdata-impl.git



	activity:
		base:		http://192.168.18.14:81/platform-architecture.activity/activity-base.git
		            git@192.168.18.14:platform-architecture.activity/activity-base.git
		mobile:		http://192.168.18.14:81/platform-architecture.activity/activity-mobile.git  (部署包)
		            git@192.168.18.14:platform-architecture.activity/activity-mobile.git
		manage:		http://192.168.18.14:81/platform-architecture.activity/activity-manage.git  (部署包)
		            git@192.168.18.14:platform-architecture.activity/activity-manage.git
		scheduler：	http://192.168.18.14:81/platform-architecture.activity/activity-scheduler.git   (部署包)
		            git@192.168.18.14:platform-architecture.activity/activity-scheduler.git
		stage:
			api:	http://192.168.18.14:81/platform-architecture.activity/activity-stage-api.git
			        git@192.168.18.14:platform-architecture.activity/activity-stage-api.git
			impl:	http://192.168.18.14:81/platform-architecture.activity/activity-stage-impl.git  (部署包)
			        git@192.168.18.14:platform-architecture.activity/activity-stage-impl.git

	asset:
		base:		http://192.168.18.14:81/platform-architecture.asset/asset-base.git
		            git@192.168.18.14:platform-architecture.asset/asset-base.git
		web:		http://192.168.18.14:81/platform-architecture.asset/asset-web.git   (部署包)
		            git@192.168.18.14:platform-architecture.asset/asset-web.git
		scheduler：	http://192.168.18.14:81/platform-architecture.asset/asset-scheduler.git (部署包)
		            git@192.168.18.14:platform-architecture.asset/asset-scheduler.git
		r360：
			api:	http://192.168.18.14:81/platform-architecture.asset/asset-r360-api.git
			        git@192.168.18.14:platform-architecture.asset/asset-r360-api.git
			impl:	http://192.168.18.14:81/platform-architecture.asset/asset-r360-impl.git (部署包)
			        git@192.168.18.14:platform-architecture.asset/asset-r360-impl.git
		cardniu:
		    api:    http://192.168.18.14:81/platform-architecture.asset/asset-cardniu-api.git
		            git@192.168.18.14:platform-architecture.asset/asset-cardniu-api.git
		    impl:   http://192.168.18.14:81/platform-architecture.asset/asset-cardniu-impl.git (部署包)
		            git@192.168.18.14:platform-architecture.asset/asset-cardniu-impl.git
	    common:
	       api:     http://192.168.18.14:81/platform-architecture.asset/asset-common-api.git
	                git@192.168.18.14:platform-architecture.asset/asset-common-api.git
	       impl:    http://192.168.18.14:81/platform-architecture.asset/asset-common-impl.git (部署包)
	                git@192.168.18.14:platform-architecture.asset/asset-common-impl.git

	shield:
		base:		http://192.168.18.14:81/platform-architecture.shield/shield-base.git
		            git@192.168.18.14:platform-architecture.shield/shield-base.git
		web:		http://192.168.18.14:81/platform-architecture.shield/shield-web.git (部署包)
		            git@192.168.18.14:platform-architecture.shield/shield-web.git
		sys:
			api:	http://192.168.18.14:81/platform-architecture.shield/shield-sys-api.git
			        git@192.168.18.14:platform-architecture.shield/shield-sys-api.git
			impl:	http://192.168.18.14:81/platform-architecture.shield/shield-sys-impl.git    (部署包)
			        git@192.168.18.14:platform-architecture.shield/shield-sys-impl.git

	ord-admin: http://192.168.18.14:81/platform-architecture/org-admin.git  (部署包)
	           git@192.168.18.14:platform-architecture/org-admin.git